displayName=Better Boss Health Bar
author=thedevchimp
description=Replaces the default boss health bar with a dynamic and customizable one.
tags=boss,health,hp,bar,hud,overlay,pvm,better,ui
plugins=com.betterbosshealthbar.BetterBossHealthBarPlugin
build=standard